// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_TcovrpfWnHCrAGQHjcsq-kdXEyHyH8w',
    appId: '1:399188688512:web:a7fb6c461c6d4ada28b065',
    messagingSenderId: '399188688512',
    projectId: 'mini-smart-home-e541e',
    authDomain: 'mini-smart-home-e541e.firebaseapp.com',
    databaseURL: 'https://mini-smart-home-e541e-default-rtdb.firebaseio.com',
    storageBucket: 'mini-smart-home-e541e.firebasestorage.app',
    measurementId: 'G-1TC4FCRRGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNJcX1urS6gld33DU3Q_PXWSFNmPCRCco',
    appId: '1:399188688512:android:64ad77d16fba303e28b065',
    messagingSenderId: '399188688512',
    projectId: 'mini-smart-home-e541e',
    databaseURL: 'https://mini-smart-home-e541e-default-rtdb.firebaseio.com',
    storageBucket: 'mini-smart-home-e541e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgqf_UUWLqsqR2CyWAH1UigrOhGypWj6w',
    appId: '1:399188688512:ios:e62e88376bc483a628b065',
    messagingSenderId: '399188688512',
    projectId: 'mini-smart-home-e541e',
    databaseURL: 'https://mini-smart-home-e541e-default-rtdb.firebaseio.com',
    storageBucket: 'mini-smart-home-e541e.firebasestorage.app',
    iosBundleId: 'com.example.minismarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgqf_UUWLqsqR2CyWAH1UigrOhGypWj6w',
    appId: '1:399188688512:ios:e62e88376bc483a628b065',
    messagingSenderId: '399188688512',
    projectId: 'mini-smart-home-e541e',
    databaseURL: 'https://mini-smart-home-e541e-default-rtdb.firebaseio.com',
    storageBucket: 'mini-smart-home-e541e.firebasestorage.app',
    iosBundleId: 'com.example.minismarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_TcovrpfWnHCrAGQHjcsq-kdXEyHyH8w',
    appId: '1:399188688512:web:515ce9912d622e5528b065',
    messagingSenderId: '399188688512',
    projectId: 'mini-smart-home-e541e',
    authDomain: 'mini-smart-home-e541e.firebaseapp.com',
    databaseURL: 'https://mini-smart-home-e541e-default-rtdb.firebaseio.com',
    storageBucket: 'mini-smart-home-e541e.firebasestorage.app',
    measurementId: 'G-MRS6183VVC',
  );
}
