// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiK0Y1yi4OrmQNz0O7VQ2jbplGwAMXWZw',
    appId: '1:285182170294:web:f16ea595075a8c06f7c217',
    messagingSenderId: '285182170294',
    projectId: 'smart-home-new-a9eb7',
    authDomain: 'smart-home-new-a9eb7.firebaseapp.com',
    databaseURL: 'https://smart-home-new-a9eb7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-new-a9eb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR1FTVY92Js7cLNhxDkPmHAFMMgzvu780',
    appId: '1:285182170294:android:61d127899b84e9c5f7c217',
    messagingSenderId: '285182170294',
    projectId: 'smart-home-new-a9eb7',
    databaseURL: 'https://smart-home-new-a9eb7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-new-a9eb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo6xqO093ssLiOMZHGkTx0gzPVDZCIMQc',
    appId: '1:285182170294:ios:723d163198a87c59f7c217',
    messagingSenderId: '285182170294',
    projectId: 'smart-home-new-a9eb7',
    databaseURL: 'https://smart-home-new-a9eb7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-new-a9eb7.firebasestorage.app',
    iosBundleId: 'com.example.minismarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo6xqO093ssLiOMZHGkTx0gzPVDZCIMQc',
    appId: '1:285182170294:ios:723d163198a87c59f7c217',
    messagingSenderId: '285182170294',
    projectId: 'smart-home-new-a9eb7',
    databaseURL: 'https://smart-home-new-a9eb7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-new-a9eb7.firebasestorage.app',
    iosBundleId: 'com.example.minismarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiK0Y1yi4OrmQNz0O7VQ2jbplGwAMXWZw',
    appId: '1:285182170294:web:e190b03f58f5ae57f7c217',
    messagingSenderId: '285182170294',
    projectId: 'smart-home-new-a9eb7',
    authDomain: 'smart-home-new-a9eb7.firebaseapp.com',
    databaseURL: 'https://smart-home-new-a9eb7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-home-new-a9eb7.firebasestorage.app',
  );
}
